
package hr.fer.tel.web_service;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.7-b01 
 * Generated source version: 2.2
 * 
 */
@WebService(name = "SensorServer", targetNamespace = "http://dz_1.rassus.tel.fer.hr/")
@SOAPBinding(style = SOAPBinding.Style.RPC)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface SensorServer {


    /**
     * 
     * @param arg3
     * @param arg2
     * @param arg4
     * @param arg1
     * @param arg0
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://dz_1.rassus.tel.fer.hr/SensorServer/registerRequest", output = "http://dz_1.rassus.tel.fer.hr/SensorServer/registerResponse")
    public boolean register(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0,
        @WebParam(name = "arg1", partName = "arg1")
        double arg1,
        @WebParam(name = "arg2", partName = "arg2")
        double arg2,
        @WebParam(name = "arg3", partName = "arg3")
        String arg3,
        @WebParam(name = "arg4", partName = "arg4")
        int arg4);

    /**
     * 
     * @param arg0
     * @return
     *     returns hr.fer.tel.web_service.UserAddress
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://dz_1.rassus.tel.fer.hr/SensorServer/searchNeighbourRequest", output = "http://dz_1.rassus.tel.fer.hr/SensorServer/searchNeighbourResponse")
    public UserAddress searchNeighbour(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0);

    /**
     * 
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://dz_1.rassus.tel.fer.hr/SensorServer/storeMeasurementRequest", output = "http://dz_1.rassus.tel.fer.hr/SensorServer/storeMeasurementResponse")
    public boolean storeMeasurement(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0,
        @WebParam(name = "arg1", partName = "arg1")
        String arg1,
        @WebParam(name = "arg2", partName = "arg2")
        float arg2);

    /**
     * 
     * @param arg0
     */
    @WebMethod
    @Action(input = "http://dz_1.rassus.tel.fer.hr/SensorServer/unregisterRequest", output = "http://dz_1.rassus.tel.fer.hr/SensorServer/unregisterResponse")
    public void unregister(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0);

}
